CREATE TABLE duenno (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(9)   NOT NULL,
    correo VARCHAR(255),
    nombre VARCHAR(255),
    CONSTRAINT uk_duenno_cedula UNIQUE (cedula)
);

CREATE INDEX idx_duenno_correo ON duenno (correo);
CREATE INDEX idx_duenno_nombre ON duenno (nombre);
