CREATE TABLE perro (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255),
    raza      VARCHAR(255),
    duenno_id BIGINT NOT NULL,
    CONSTRAINT fk_perro_duenno FOREIGN KEY (duenno_id) REFERENCES duenno (id)
);

CREATE INDEX idx_perro_duenno_id ON perro (duenno_id);
