CREATE TABLE producto (
                       id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre    VARCHAR(255) NOT NULL,
                       descripcion      VARCHAR(255),
                       precio NUMERIC(10, 2) NOT NULL,
                       cantidad_stock INTEGER NOT NULL,
                       categoria_id BIGINT NOT NULL,
                       CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE INDEX idx_producto_categoria_id ON producto (categoria_id);